"""Explain the sim-vs-live trade-count gap from the StrategySignal audit.

Aggregates the live `StrategySignal` table (one row per signal generated by
a strategy runner, logged inside `entry_manager.place_entry()`) per
strategy name, for comparison against the sim's trade count. Uses the same
+5:30 IST-skew window treatment `live_deltas.live_summary` applies to
Position.created_at, since StrategySignal.signal_at is written by the same
get_kolkata_time() naive-wall-clock convention.
"""
from __future__ import annotations

from collections import Counter
from datetime import datetime, timedelta

from shared.models import Strategy, StrategySignal

_IST_SKEW = timedelta(hours=5, minutes=30)


def reconcile(session, strategy_names: list[str], start_utc: datetime,
             end_utc: datetime, sim_counts: dict[str, int]) -> dict[str, dict | str]:
    """Per-strategy signal-generation/placement/rejection audit vs sim trades.

    Returns {name: {"live_generated", "live_placed", "rejected": {reason:
    n}, "sim_trades"}}, or the string "unavailable" for a name with no
    StrategySignal rows in the window (distinct from a name with rows but
    zero PLACED/REJECTED of a given kind).
    """
    lo = start_utc.replace(tzinfo=None) + _IST_SKEW
    hi = end_utc.replace(tzinfo=None) + _IST_SKEW

    rows = (
        session.query(Strategy.name, StrategySignal.status,
                      StrategySignal.rejection_reason)
        .join(Strategy, StrategySignal.strategy_id == Strategy.id)
        .filter(
            Strategy.name.in_(strategy_names),
            StrategySignal.signal_at >= lo,
            StrategySignal.signal_at <= hi,
        )
        .all()
    )

    by_name: dict[str, list] = {}
    for name, status, reason in rows:
        by_name.setdefault(name, []).append((status, reason))

    out: dict[str, dict | str] = {}
    for name in strategy_names:
        recs = by_name.get(name)
        if not recs:
            out[name] = "unavailable"
            continue
        placed = sum(1 for status, _ in recs if status == "PLACED")
        rejected = Counter(
            reason or "unknown" for status, reason in recs if status == "REJECTED")
        out[name] = {
            "live_generated": len(recs),
            "live_placed": placed,
            "rejected": dict(rejected),
            "sim_trades": int(sim_counts.get(name, 0)),
        }
    return out
